[package]
name = "bitcoin_slices"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitcoin_hashes = { version="0.11.0", optional = true }

[features]
default = [ "hashes" ]
hashes = [ "bitcoin_hashes" ]

[dev-dependencies]
hex_lit = {version = "0.1.1", features = [ "rust_v_1_46" ] }
bitcoin = { version="0.29.1", features = [ "rand" ] }
